'use strict';

module.exports = [
    '/classreport/courseReport.json',
    '/classreport/joinClassReport.json',
    '/report/categoryReport.json',
    '/report/incomeReport.json',
    '/report/provinceReport.json',
    '/report/cityReport.json',
    '/report/increasedComment.json',
    '/report/increasedOrg.json',
    '/wechat/staff/checkinList.ajax',
    '/wechat/staff/checkinDetail.ajax',
    '/wechat/staff/manualSign.ajax',
    '/wechat/staff/scanCodeSign.ajax',
    '/wechat/student/studentInfo.ajax',
    '/wechat/student/lessons.ajax',
    '/wechat/student/classes.ajax',
    '/wechat/student/classDetail.ajax',
    '/wechat/student/modifyReceipt.ajax',
    '/wechat/student/contracts.ajax',
    '/wechat/student/consumeRecord.ajax',
    '/wechat/teacher/teacherInfo.ajax',
    '/wechat/teacher/classes.ajax',
    '/wechat/teacher/classDetail.ajax',
    '/wechat/webauth/selectStu.ajax',
    '/wechat/webauth/studentCenter.ajax',
    '/wechat/webauth/staffCenter.ajax',
    '/wechat/webauth/bind.ajax',
    '/wechat/common/unbind.ajax',
    '/wechat/common/modifyHeadImg.ajax',
    '/wechat/common/upload.ajax'
]
